apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-binding
subjects:
- kind: ServiceAccount
  name: my-reader
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
